### ISSUE TITLE
Pattern Ordering on Search Page

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#170]
#63 #49 #130 

Patterns should be in alpha order from A-Z (and 0-9, if ever applicable) whether results are filtered or unfiltered.

**Comment by mbr4nt** [comment]
@mcinnisb Direction i got from @WilliamsHeidi was to sort by supplier (allsteel, hbf, etc) then patter type (solid, texture, etc). waiting on direction.

**Comment by mcinnisb** [comment]
We will need to the set the order at some point. Current expectations are that they will sort the way we want them, not alphabetical. Due to complexity of setting the sort order we may have to push this to the week after launch, but would ideal to have it before launch.

Brandon McInnis
Director, e-Business

Allsteel
Mobile 563.299.2885
mcinnisb@allsteeloffice.com<http://www.allsteeloffice.com/>
allsteeloffice.com<http://www.allsteeloffice.com/>

**Comment by mcinnisb** [comment]
Sort orders have all been corrected.

**Comment by scholfieldk** [comment]
Need to remove supplier dependency form sort order so all A-Z (ex: Abito- HBF, Allsteel Leather, Appoint- allsteel) and 0-9 fabrics are together.

**Comment by mcinnisb** [comment]
Closing this bug per a conversation with Kandice. Sort order once facets are filtered is correct as is. The default sort when you first click on "Textiles" will be Brand, then Aphabetical.
