### ISSUE TITLE
Textiles Search Page - Straight Plush

### ISSUE THREAD

**Issue by WilliamsHeidi** [Allsteel/hni-textiles-webcomponents#255]
Straight Plush is showing as a Pattern Name but there are no color tiles under it.

**Comment by tucaz** [comment]
Currently in existing production T&F there are also no colors under Straight Plush. The PDW export also contains no color for this family. This seems to be a data problem before PDW.

@WilliamsHeidi would you please work with @garrettbt to fix this (if possible. Otherwise maybe we should remove it?) so I can update the data once its ready.

**Comment by garrettbt** [comment]
All color-ways for Straight Plush are marked as discontinued in the PDW. I have discontinued the fabric family but am already in the process of a syndication that was asked for yesterday.

**Comment by WilliamsHeidi** [comment]
@SorensenK Can you verify that Straight Plush is discontinued?

**Comment by SorensenK** [comment]
@WilliamsHeidi yes, it is discontinued
