### ISSUE TITLE
Searching for Green

### ISSUE THREAD

**Issue by hamiltonk** [Allsteel/hni-textiles-webcomponents#26]
When searching "green" from the fabrics search page, results that are not green are returned. That did not happen with blue, red, yellow, brown or black.

![green_search_01](https://cloud.githubusercontent.com/assets/14330996/10485628/d0a7ccca-7250-11e5-8d62-322632af0525.png)

**Comment by mbr4nt** [comment]
This is because those fabrics have the word green in some property value. For instance, this I-Beam family has 'Finish: "Crypton® Green",'.

Those will always show up. What I'll do is to open an issue on the API project asking to boost relevancy on the colorFamily field, so that the true green stuff comes first.
